// Generated by ts-to-zod
import { z } from "zod";
import { type MantineStylesApi } from "./accordion.schema-input";

export const mantineStylesApiValueSchema = z.union([z.string(), z.number(), z.boolean()]).nullable();

export const mantineStylesApiSchema: z.ZodSchema<MantineStylesApi> = z.lazy(() => z.record(z.string(), z.union([z.record(z.string(), z.union([mantineStylesApiValueSchema, mantineStylesApiSchema, z.array(mantineStylesApiValueSchema)])), z.undefined()])));

export const mantineAccordionPropsSchema = z.strictObject({
    styles: mantineStylesApiSchema.optional()
});
