// Generated by ts-to-zod
import { z } from "zod";

export const mantineSpacingSchema = z.union([z.literal("xs"), z.literal("sm"), z.literal("md"), z.literal("lg"), z.literal("xl"), z.string(), z.number()]);

export const mantineResponsiveCssSizeSchema = z.union([z.string(), z.number(), z.object({
        base: z.union([z.string(), z.number()]).optional(),
        xs: z.union([z.string(), z.number()]).optional(),
        sm: z.union([z.string(), z.number()]).optional(),
        md: z.union([z.string(), z.number()]).optional(),
        lg: z.union([z.string(), z.number()]).optional(),
        xl: z.union([z.string(), z.number()]).optional()
    })]);

export const mantineButtonPropsSchema = z.strictObject({
    fw: z.union([z.string(), z.number()]).optional(),
    mt: mantineSpacingSchema.optional(),
    fz: mantineResponsiveCssSizeSchema.optional(),
    h: mantineResponsiveCssSizeSchema.optional(),
    variant: z.string().optional(),
    size: mantineSpacingSchema.optional(),
    fullWidth: z.boolean().optional()
});
