// Generated by ts-to-zod
import { z } from "zod";
import { type MantineStylesApi } from "./group";

export const mantineCssLengthSchema = z.union([z.string(), z.number()]);

export const mantineFlexWrapSchema = z.union([z.literal("nowrap"), z.literal("wrap"), z.literal("wrap-reverse")]);

export const mantineSpacingSchema = z.union([z.literal("xs"), z.literal("sm"), z.literal("md"), z.literal("lg"), z.literal("xl"), z.string(), z.number()]);

export const mantineStylesApiValueSchema = z.union([z.string(), z.number(), z.boolean()]).nullable();

export const mantineStylesApiSchema: z.ZodSchema<MantineStylesApi> = z.lazy(() => z.record(z.string(), z.union([z.record(z.string(), z.union([mantineStylesApiValueSchema, mantineStylesApiSchema, z.array(mantineStylesApiValueSchema)])), z.undefined()])));

export const mantineGroupPropsSchema = z.strictObject({
    w: mantineCssLengthSchema.optional(),
    h: mantineCssLengthSchema.optional(),
    justify: z.string().optional(),
    wrap: mantineFlexWrapSchema.optional(),
    p: mantineSpacingSchema.optional(),
    pt: mantineSpacingSchema.optional(),
    pb: mantineSpacingSchema.optional(),
    styles: mantineStylesApiSchema.optional()
});
