// Generated by ts-to-zod
import { z } from "zod";
import { mantineCssLengthSchema, mantineFlexWrapSchema, mantineStylesApiSchema } from "./primitives.zod";
import { mantineSpacingSchema } from "./spacing.zod";

export const mantineGroupPropsSchema = z.strictObject({
    w: mantineCssLengthSchema.optional(),
    h: mantineCssLengthSchema.optional(),
    justify: z.string().optional(),
    wrap: mantineFlexWrapSchema.optional(),
    p: mantineSpacingSchema.optional(),
    pt: mantineSpacingSchema.optional(),
    pb: mantineSpacingSchema.optional(),
    styles: mantineStylesApiSchema.optional()
});
