// Generated by ts-to-zod
import {z} from "zod";

export const mantineFloatingPositionSchema = z.union([
	z.literal("top"),
	z.literal("right"),
	z.literal("bottom"),
	z.literal("left"),
	z.literal("top-start"),
	z.literal("top-end"),
	z.literal("bottom-start"),
	z.literal("bottom-end"),
	z.literal("left-start"),
	z.literal("left-end"),
	z.literal("right-start"),
	z.literal("right-end"),
]);

export const mantineMenuPropsSchema = z.strictObject({
	shadow: z.string().optional(),
	position: mantineFloatingPositionSchema.optional(),
});
