// Generated by ts-to-zod
import { z } from "zod";
import { mantineSpacingSchema } from "./spacing.zod";

export const mantinePaperPropsSchema = z.strictObject({
    withBorder: z.boolean().optional(),
    shadow: z.string().optional(),
    px: mantineSpacingSchema.optional(),
    py: mantineSpacingSchema.optional(),
    style: z.record(z.string(), z.union([z.string(), z.number()])).optional()
});
