// Generated by ts-to-zod
import { z } from "zod";
import { type MantineStylesApi } from "./primitives.schema-input";

export const mantineCssLengthSchema = z.union([z.string(), z.number()]);

export const mantineFlexWrapSchema = z.union([z.literal("nowrap"), z.literal("wrap"), z.literal("wrap-reverse")]);

export const mantineStylesApiValueSchema = z.union([z.string(), z.number(), z.boolean()]).nullable();

export const mantineStylesApiSchema: z.ZodSchema<MantineStylesApi> = z.lazy(() => z.record(z.string(), z.union([z.record(z.string(), z.union([mantineStylesApiValueSchema, mantineStylesApiSchema, z.array(mantineStylesApiValueSchema)])), z.undefined()])));

export const mantineResponsiveCssSizeSchema = z.union([z.string(), z.number(), z.object({
        base: z.union([z.string(), z.number()]).optional(),
        xs: z.union([z.string(), z.number()]).optional(),
        sm: z.union([z.string(), z.number()]).optional(),
        md: z.union([z.string(), z.number()]).optional(),
        lg: z.union([z.string(), z.number()]).optional(),
        xl: z.union([z.string(), z.number()]).optional()
    })]);
