// Generated by ts-to-zod
import { z } from "zod";

export const mantineSpacingSchema = z.union([z.literal("xs"), z.literal("sm"), z.literal("md"), z.literal("lg"), z.literal("xl"), z.string(), z.number()]);

export const mantineStackPropsSchema = z.strictObject({
    gap: mantineSpacingSchema.optional(),
    p: mantineSpacingSchema.optional(),
    align: z.string().optional(),
    justify: z.string().optional()
});
