// Generated by ts-to-zod
import { z } from "zod";

export const mantineTooltipPropsSchema = z.strictObject({
    label: z.string().optional(),
    withArrow: z.boolean().optional(),
    position: z.string().optional(),
    withinPortal: z.boolean().optional(),
    color: z.string().optional(),
    radius: z.union([z.string(), z.number()]).optional(),
    multiline: z.boolean().optional(),
    zIndex: z.number().optional()
});
