// Generated by ts-to-zod
import { z } from "zod";
import { mantineSpacingSchema } from "./spacing.zod";

export const mantineTooltipPropsSchema = z.strictObject({
    label: z.string().optional(),
    withArrow: z.boolean().optional(),
    position: z.string().optional(),
    withinPortal: z.boolean().optional(),
    color: z.string().optional(),
    radius: mantineSpacingSchema.optional(),
    multiline: z.boolean().optional(),
    zIndex: z.number().optional()
});
